package com.example.echolex.core.constants

//Repeating
const val MIN_COUNT_OF_CARDS_FOR_REPEATING = 5
const val STANDARD_COUNT_OF_CARDS_FOR_REPEATING = 10
const val MAX_COUNT_OF_CARDS_FOR_REPEATING = 40

const val MIN_COUNT_OF_CORRECT_CYCLES_FOR_REPEATING = 3
const val STANDARD_COUNT_OF_CORRECT_CYCLES_FOR_REPEATING = 5
const val MAX_COUNT_OF_CORRECT_CYCLES_FOR_REPEATING = 10


//Learning
const val MIN_COUNT_OF_CARDS_FOR_LEARNING = 3
const val STANDARD_COUNT_OF_CARDS_FOR_LEARNING = 10
const val MAX_COUNT_OF_CARDS_FOR_LEARNING = 15

const val MIN_COUNT_OF_CORRECT_CYCLES_FOR_LEARNING = 2
const val STANDARD_COUNT_OF_CORRECT_CYCLES_FOR_LEARNING = 10
const val MAX_COUNT_OF_CORRECT_CYCLES_FOR_LEARNING = 5

const val MIN_COUNT_REPEATING_PRIORITY = 0
const val STANDARD_COUNT_REPEATING_PRIORITY = 0
const val MAX_COUNT_REPEATING_PRIORITY = COUNT_OF_REPETITION_TO_LEARN



//Blueprint validation constants
const val MIN_BLUEPRINT_NAME_LENGTH = 3
const val MAX_BLUEPRINT_NAME_LENGTH = 15
